/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shaice.bigdata.superwebanalytics.schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-07-12")
public class PersonProperty implements org.apache.thrift.TBase<PersonProperty, PersonProperty._Fields>, java.io.Serializable, Cloneable, Comparable<PersonProperty> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PersonProperty");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PERPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("perperty", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PersonPropertyStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PersonPropertyTupleSchemeFactory();

  private @org.apache.thrift.annotation.Nullable PersonID id; // required
  private @org.apache.thrift.annotation.Nullable PagePropertyValue perperty; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    PERPERTY((short)2, "perperty");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // PERPERTY
          return PERPERTY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PersonID.class)));
    tmpMap.put(_Fields.PERPERTY, new org.apache.thrift.meta_data.FieldMetaData("perperty", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PagePropertyValue.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PersonProperty.class, metaDataMap);
  }

  public PersonProperty() {
  }

  public PersonProperty(
    PersonID id,
    PagePropertyValue perperty)
  {
    this();
    this.id = id;
    this.perperty = perperty;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PersonProperty(PersonProperty other) {
    if (other.is_set_id()) {
      this.id = new PersonID(other.id);
    }
    if (other.is_set_perperty()) {
      this.perperty = new PagePropertyValue(other.perperty);
    }
  }

  public PersonProperty deepCopy() {
    return new PersonProperty(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.perperty = null;
  }

  @org.apache.thrift.annotation.Nullable
  public PersonID get_id() {
    return this.id;
  }

  public void set_id(@org.apache.thrift.annotation.Nullable PersonID id) {
    this.id = id;
  }

  public void unset_id() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean is_set_id() {
    return this.id != null;
  }

  public void set_id_isSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public PagePropertyValue get_perperty() {
    return this.perperty;
  }

  public void set_perperty(@org.apache.thrift.annotation.Nullable PagePropertyValue perperty) {
    this.perperty = perperty;
  }

  public void unset_perperty() {
    this.perperty = null;
  }

  /** Returns true if field perperty is set (has been assigned a value) and false otherwise */
  public boolean is_set_perperty() {
    return this.perperty != null;
  }

  public void set_perperty_isSet(boolean value) {
    if (!value) {
      this.perperty = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unset_id();
      } else {
        set_id((PersonID)value);
      }
      break;

    case PERPERTY:
      if (value == null) {
        unset_perperty();
      } else {
        set_perperty((PagePropertyValue)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return get_id();

    case PERPERTY:
      return get_perperty();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return is_set_id();
    case PERPERTY:
      return is_set_perperty();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PersonProperty)
      return this.equals((PersonProperty)that);
    return false;
  }

  public boolean equals(PersonProperty that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.is_set_id();
    boolean that_present_id = true && that.is_set_id();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_perperty = true && this.is_set_perperty();
    boolean that_present_perperty = true && that.is_set_perperty();
    if (this_present_perperty || that_present_perperty) {
      if (!(this_present_perperty && that_present_perperty))
        return false;
      if (!this.perperty.equals(that.perperty))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((is_set_id()) ? 131071 : 524287);
    if (is_set_id())
      hashCode = hashCode * 8191 + id.hashCode();

    hashCode = hashCode * 8191 + ((is_set_perperty()) ? 131071 : 524287);
    if (is_set_perperty())
      hashCode = hashCode * 8191 + perperty.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PersonProperty other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(is_set_id()).compareTo(other.is_set_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_perperty()).compareTo(other.is_set_perperty());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_perperty()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.perperty, other.perperty);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PersonProperty(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("perperty:");
    if (this.perperty == null) {
      sb.append("null");
    } else {
      sb.append(this.perperty);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!is_set_id()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' is unset! Struct:" + toString());
    }

    if (!is_set_perperty()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'perperty' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PersonPropertyStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PersonPropertyStandardScheme getScheme() {
      return new PersonPropertyStandardScheme();
    }
  }

  private static class PersonPropertyStandardScheme extends org.apache.thrift.scheme.StandardScheme<PersonProperty> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PersonProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.id = new PersonID();
              struct.id.read(iprot);
              struct.set_id_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PERPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.perperty = new PagePropertyValue();
              struct.perperty.read(iprot);
              struct.set_perperty_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PersonProperty struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        struct.id.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.perperty != null) {
        oprot.writeFieldBegin(PERPERTY_FIELD_DESC);
        struct.perperty.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PersonPropertyTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PersonPropertyTupleScheme getScheme() {
      return new PersonPropertyTupleScheme();
    }
  }

  private static class PersonPropertyTupleScheme extends org.apache.thrift.scheme.TupleScheme<PersonProperty> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PersonProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id.write(oprot);
      struct.perperty.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PersonProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id = new PersonID();
      struct.id.read(iprot);
      struct.set_id_isSet(true);
      struct.perperty = new PagePropertyValue();
      struct.perperty.read(iprot);
      struct.set_perperty_isSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

